export const SHOW_LOADER = 'SHOW_LOADER'
export const ADD_TASK = 'ADD_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const FETCH_TASKS = 'FETCH_TASKS'
export const EDIT_TASK = 'EDIT_TASK'
export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'